security:
    encoders:
    # mettre plutôt en algorithm auto ?? cf. https://symfony.com/doc/current/security.html
        App\Entity\User:
            algorithm: bcrypt
        App\Entity\Administrator:
            algorithm: bcrypt
            
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
        
        in_database:
            entity:
                class: App\Entity\User
                property: email
                
        in_globalbase:
            entity:
                class: App\Entity\Administrator
                property: username
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
      
      
        main:
            anonymous: true
            
            provider: in_database
            
            form_login:
                login_path: security_connexion
                check_path: security_connexion
           
                
            logout:
                path: security_disconnect
                target: blog
        
        
        # Premier test d'authentification de l'administrateur (dysfonction pour le moment....!)   
        admin:
            anonymous: true
            
            provider: in_globalbase
            
            form_login:
                login_path: connect_admin
                check_path: connect_admin
           
                
            logout:
                path: nosession
                target: blog
                
                
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
